apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta7-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ta7
      track: stable
  template:
    metadata:
      labels:
        app: ta7
        track: stable
    spec:
      containers:
        - name: app
          image: ghcr.io/jrcs1703/ta7-automation:1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
